### ISSUE TITLE
No se agrega la biblioteca para el wrapper de maven

### ISSUE THREAD

**Issue by erik-valdivieso** [kukulkan-project/kukulkan-shell#11]

**Comment by erik-valdivieso** [comment]
resuelto por @robertovillarejo

**Comment by robertovillarejo** [comment]
Resuelto en [add maven wrapper jar](https://github.com/kukulkan-project/kukulkan-generator-angularjs/commit/aa8501c480b46a91f8a7eff1c987730bd777f453)
